wolfssl_ref: auto
openssl_ref: auto
curl_ref: [ master 'curl-8_4_0', 'curl-7_88_1' ]
grpc_ref:
  - v1.60.0
# Additional refs can be added here
tests: >
  bad_ssl_alpn_test bad_ssl_cert_test client_ssl_test
  crl_ssl_transport_security_test server_ssl_test
  ssl_transport_security_test ssl_transport_security_utils_test
  test_core_security_ssl_credentials_test test_cpp_end2end_ssl_credentials_test
  h2_ssl_cert_test h2_ssl_session_reuse_test
force_fail: [ WOLFPROV_FORCE_FAIL=1, "" ]
debug: [ WOLFPROV_DEBUG=1, "" ]
