name: Build and Push Docker Image

# START OF COMMON SECTION
on:
  push:
    branches: [ '*' ]
    paths:
      - '.github/scripts/docker/Dockerfile'
      - '.github/workflows/build-docker.yml'
  pull_request:
    branches: [ '*' ]
    paths:
      - '.github/scripts/docker/Dockerfile'
      - '.github/workflows/build-docker.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/build-wolfprovider-debian
          tags: |
            type=raw,value=bookworm
            type=raw,value=latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/scripts/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
