name: HAProxy Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    name: Build wolfProvider
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      matrix:
        wolfssl_ref: [ 'master', 'v5.7.4-stable' ]
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4

      # Check if this version of wolfssl/wolfprovider has already been built,
      # mark to cache these items on post if we do end up building
      - name: Checking wolfSSL/wolfProvider in cache
        uses: actions/cache@v4
        id: wolfprov-cache
        with:
          path: |
            wolfssl-source
            wolfssl-install
            wolfprov-install
            provider.conf

          key: wolfprov-${{ matrix.wolfssl_ref }}-${{ github.sha }}
          lookup-only: true

      # If wolfssl/wolfprovider have not yet been built, pull ossl from cache
      - name: Checking OpenSSL in cache
        if: steps.wolfprov-${{ matrix.wolfssl_ref }}-cache.hit != 'true'
        uses: actions/cache@v4
        id: openssl-cache
        with:
          path: |
            openssl-source
            openssl-install

          key: ossl-depends

      # If not yet built this version, build it now
      - name: Build wolfProvider
        if: steps.wolfprov-${{ matrix.wolfssl_ref }}-cache.hit != 'true'
        run: |
          WOLFSSL_TAG=${{ matrix.wolfssl_ref }} ./scripts/build-wolfprovider.sh

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi

  test_haproxy:
    runs-on: ubuntu-22.04
    needs: build_wolfprovider
    # This should be a safe limit for the tests to run.
    timeout-minutes: 20
    strategy:
      matrix:
<<<<<<< HEAD
        # List of refs to test
        ref: [ master ]
=======
        haproxy_ref: [ 'master', '2.8' ]
        wolfssl_ref: [ 'master', 'v5.7.4-stable' ]
>>>>>>> 6ac5ab1 (Add additional CI workflows based on wolfssl patterns)
    steps:
      - name: Retrieving OpenSSL from cache
        uses: actions/cache/restore@v4
        id: openssl-cache
        with:
          path: |
            openssl-source
            openssl-install

          key: ossl-depends
          fail-on-cache-miss: true

      - name: Retrieving wolfSSL/wolfProvider from cache
        uses: actions/cache/restore@v4
        id: wolfprov-cache
        with:
          path: |
            wolfssl-source
            wolfssl-install
            wolfprov-install
            provider.conf

<<<<<<< HEAD
          key: wolfprov-${{ matrix.ref }}-${{ github.sha }}
=======
          key: wolfprov-${{ matrix.wolfssl_ref }}-${{ github.sha }}
>>>>>>> 6ac5ab1 (Add additional CI workflows based on wolfssl patterns)
          fail-on-cache-miss: true

      - name: Install HAProxy dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcre3-dev zlib1g-dev

<<<<<<< HEAD
      - name: Checkout VTest
        uses: actions/checkout@v4
        with:
          repository: vtest/VTest
          path: VTest

      - name: Build VTest
        working-directory: VTest
        # Special flags due to: https://github.com/vtest/VTest/issues/12
        run: make FLAGS='-O2 -s -Wall'

      - name: Checkout HaProxy
        uses: actions/checkout@v4
        with:
          repository: haproxy/haproxy
          path: haproxy
          ref: ${{ matrix.ref }}

      - name: Build HaProxy
        working-directory: haproxy
        run: >-
          make -j TARGET=linux-glibc
          USE_OPENSSL=1
          SSL_INC=$GITHUB_WORKSPACE/openssl-install/include/
          SSL_LIB=$GITHUB_WORKSPACE/openssl-install/lib64/
          ADDLIB=-Wl,-rpath=$GITHUB_WORKSPACE/openssl-install/lib64
=======
      - name: Build HAProxy
        uses: wolfSSL/actions-build-autotools-project@v1
        with:
          repository: haproxy/haproxy
          path: haproxy
          ref: ${{ matrix.haproxy_ref }}
          configure: USE_OPENSSL=1 SSL_INC=$GITHUB_WORKSPACE/openssl-install/include SSL_LIB=$GITHUB_WORKSPACE/openssl-install/lib64
          check: false
>>>>>>> 6ac5ab1 (Add additional CI workflows based on wolfssl patterns)

      - name: Test HAProxy with wolfProvider
        working-directory: haproxy
        run: |
<<<<<<< HEAD
          # Set up the environment for wolfProvider
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/wolfssl-install/lib:$GITHUB_WORKSPACE/openssl-install/lib64
          export OPENSSL_CONF=$GITHUB_WORKSPACE/provider.conf
          export OPENSSL_MODULES=$GITHUB_WORKSPACE/wolfprov-install/lib

          # Show HAProxy version and OpenSSL information
          ./haproxy -vv

          # Run tests exactly like wolfSSL does
          make reg-tests reg-tests/ssl VTEST_PROGRAM=$GITHUB_WORKSPACE/VTest/vtest
=======
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/wolfssl-install/lib:$GITHUB_WORKSPACE/openssl-install/lib64
          export OPENSSL_CONF=$GITHUB_WORKSPACE/provider.conf
          export OPENSSL_MODULES=$GITHUB_WORKSPACE/wolfprov-install/lib
          ./haproxy -vv
          make reg-tests REGTESTS_TYPES=ssl
>>>>>>> 6ac5ab1 (Add additional CI workflows based on wolfssl patterns)
