name: Multi-Compiler Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    name: Build with ${{ matrix.CC }}
    runs-on: ${{ matrix.OS }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-24.04-arm]
        openssl_ref: [ 'master', 'openssl-3.5.0' ]
        include:
          - CC: gcc-9
            CXX: g++-9
            wolfssl_ref: master
          - CC: gcc-10
            CXX: g++-10
            wolfssl_ref: master
          - CC: gcc-10
            CXX: g++-10
            wolfssl_ref: v5.8.0-stable
          - CC: gcc-11
            CXX: g++-11
            wolfssl_ref: master
          - CC: gcc-12
            CXX: g++-12
            wolfssl_ref: master
          - CC: clang-12
            CXX: clang++-12
            wolfssl_ref: master
          - CC: clang-13
            CXX: clang++-13
            wolfssl_ref: master
          - CC: clang-14
            CXX: clang++-14
            wolfssl_ref: master
          - CC: clang-15
            CXX: clang++-15
            wolfssl_ref: master
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.CC }} ${{ matrix.CXX }} automake libtool

      - name: Retrieving wolfSSL/wolfProvider from cache
        uses: actions/cache/restore@v4
        id: wolfprov-cache
        with:
          path: |
            scripts
            wolfssl-source
            wolfssl-install
            wolfprov-install
            openssl-install
            provider.conf

          key: wolfprov-${{ matrix.os }}-${{ matrix.wolfssl_ref }}-${{ matrix.openssl_ref }}-${{ github.sha }}
          fail-on-cache-miss: true

      # If not yet built this version, build it now
      - name: Build wolfProvider
        if: steps.wolfprov-cache.outputs.cache-hit != 'true'
        env:
          CC: ${{ matrix.CC }}
          CXX: ${{ matrix.CXX }}
        run: |
          OPENSSL_TAG=${{ matrix.openssl_ref }} WOLFSSL_TAG=${{ matrix.wolfssl_ref }} ./scripts/build-wolfprovider.sh

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ]; then
            cat test-suite.log
          fi
          if [ -f config.log ]; then
            cat config.log
          fi
