name: Multithread Test

# START OF COMMON SECTION
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  make_check:
    name: multithread test
    runs-on: ubuntu-latest
    # This should be a safe limit for the tests to run.
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Checkout wolfProvider

      - name: Test wolfProvider multithreaded
        run: |
          WOLFPROV_CONFIG_CFLAGS="-DTEST_MULTITHREADED" ./scripts/build-wolfprovider.sh
          make test

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
