name: OpenLDAP Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    uses: ./.github/workflows/build-wolfprovider.yml
    with:
      os_ref: ${{ matrix.os_ref }}
      wolfssl_ref: ${{ matrix.wolfssl_ref }}
      openssl_ref: ${{ matrix.openssl_ref }}
    strategy:
      matrix:
        os_ref: [ 'ubuntu-22.04', 'ubuntu-24.04-arm' ]
        wolfssl_ref: [ 'master', 'v5.8.0-stable' ]
        openssl_ref: [ 'openssl-3.5.0' ]

  test_openldap:
    needs: build_wolfprovider
    # This should be a safe limit for the tests to run.
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os_ref: [ 'ubuntu-22.04', 'ubuntu-24.04-arm' ]
        openldap_ref: [ 'master', 'OPENLDAP_REL_ENG_2_5_13', 'OPENLDAP_REL_ENG_2_6_7' ]
        wolfssl_ref: [ 'master', 'v5.8.0-stable' ]
        openssl_ref: [ 'openssl-3.5.0' ]
    runs-on: ${{ matrix.os_ref }}
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Retrieving wolfSSL/wolfProvider from cache
        uses: actions/cache/restore@v4
        id: wolfprov-cache
        with:
          path: |
            scripts
            wolfssl-source
            wolfssl-install
            wolfprov-install
            openssl-install
            provider.conf

          key: wolfprov-${{ matrix.os_ref  }}-${{ matrix.wolfssl_ref }}-${{ matrix.openssl_ref }}-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsasl2-dev

      - name: Checkout openldap
        uses: actions/checkout@v4
        with:
          repository: openldap/openldap
          path: openldap
          ref: ${{ matrix.openldap_ref }}

      - name: Build and test OpenLDAP with wolfProvider
        working-directory: openldap
        run: |
          # Set up the environment for wolfProvider
          source $GITHUB_WORKSPACE/scripts/env-setup

          # Generate configure script
          rm -f aclocal.m4
          autoreconf -ivf

          # Configure with OpenSSL
          ./configure --with-tls=openssl --disable-bdb --disable-hdb \
            CFLAGS="-I$GITHUB_WORKSPACE/openssl-install/include \
              -L$GITHUB_WORKSPACE/openssl-install/lib64" \
            LDFLAGS="-Wl,-rpath,$GITHUB_WORKSPACE/openssl-install/lib64"

          # Build OpenLDAP
          make -j depend
          make -j
          make -j check
