name: qtbase Network Tests
on:
  push:
    branches: [ 'master', 'main', 'release/**', 'qt5network5' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wolfprovider:
    uses: ./.github/workflows/build-wolfprovider.yml
    with:
      wolfssl_ref: ${{ matrix.wolfssl_ref }}
      openssl_ref: ${{ matrix.openssl_ref }}
    strategy:
      matrix:
        # Test 5.8.2 since our .deb is based on that version
        wolfssl_ref: [ 'v5.8.2-stable' ]
        openssl_ref: [ 'openssl-3.5.0' ]

  test_qtbase_network:
    runs-on: ubuntu-22.04
    needs: build_wolfprovider
    timeout-minutes: 30
    container:
      image: debian:bookworm
      env:
        DEBIAN_FRONTEND: noninteractive
    strategy:
      matrix:
        # Test 5.8.2 since our .deb is based on that version
        qt_ref: [ 'v5.15.8-lts-lgpl' ]
        wolfssl_ref: [ 'v5.8.2-stable' ]
        openssl_ref: [ 'openssl-3.5.0' ]
        force_fail: [ 'WOLFPROV_FORCE_FAIL=1', '' ]
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download wolfSSL packages
        uses: actions/download-artifact@v4
        with:
          name: wolfssl-debian-packages-${{ github.sha }}
          path: /tmp/wolfssl-artifacts

      - name: Download OpenSSL/wolfProvider packages
        uses: actions/download-artifact@v4
        with:
          name: openssl-wolfprov-debian-packages-${{ github.sha }}
          path: /tmp/openssl-wolfprov-artifacts

      - name: Install wolfSSL/OpenSSL/wolfprov packages
        run: |
          $GITHUB_WORKSPACE/.github/scripts/install-packages.sh

      - name: Install Qt dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y python3 perl libpcre2-dev \
            zlib1g-dev cmake ninja-build
      
      - name: Checkout Qt
        uses: actions/checkout@v4
        with:
          repository: qt/qtbase
          path: qt5_repo
          ref: ${{ matrix.qt_ref }}
          fetch-depth: 1

      - name: Checkout OSP
        uses: actions/checkout@v4
        with:
          repository: wolfssl/osp
          path: osp
          fetch-depth: 1

      - name: Configure Qt
        working-directory: qt5_repo
        run: |          
          # Configure Qt with GUI support to avoid test dependency issues
          # Build with GUI support but skip examples and DBus
          ./configure -opensource -confirm-license -developer-build \
            -nomake examples -no-dbus -no-opengl \
            -openssl-linked

      - name: Build Qt (v5.15.8 - qmake)
        working-directory: qt5_repo
        run: |
          # Force C++14 to avoid C++17 compatibility issues
          echo 'QMAKE_CXXFLAGS += -std=c++14' >> mkspecs/linux-g++/qmake.conf

          make -k -j$(nproc)

      - name: Add test server to hosts
        run: |
          sudo sh -c 'echo "127.0.0.1 qt-test-server.qt-test-net" >> /etc/hosts'

      - name: Run QSSLSocket test
        working-directory: qt5_repo
        shell: bash
        run: |
          # wolfProvider is already loaded as the default provider
          echo "Current OpenSSL providers:"
          openssl list -providers
          openssl list -providers | grep -q "wolfSSL Provider" || (echo "ERROR: libwolfprov not found in OpenSSL providers" && exit 1)
          export ${{ matrix.force_fail }}
          if [ -n "${{ matrix.force_fail }}" ]; then
            set +e
          fi

          # Run the QSSLSocket test, the make check takes too long
          QTEST_ENVIRONMENT=ci ./tests/auto/network/ssl/qsslsocket/tst_qsslsocket 2>&1 | tee qsslsocket-test.log
          if grep -q "521 passed" qsslsocket-test.log; then
            TEST_RESULT=0
          else
            TEST_RESULT=1
            echo "Tests failed unexpectedly for 'v5.15.8-lts-lgpl' branch."
          fi
          $GITHUB_WORKSPACE/.github/scripts/check-workflow-result.sh $TEST_RESULT ${{ matrix.force_fail }} qtbase-qsslsocket
