name: rsync Tests
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wolfprovider:
    uses: ./.github/workflows/build-wolfprovider.yml
    with:
      wolfssl_ref: ${{ matrix.wolfssl_ref }}
      openssl_ref: ${{ matrix.openssl_ref }}
    strategy:
      matrix:
        # Test 5.8.2 since our .deb is based on that version
        wolfssl_ref: [ 'v5.8.2-stable' ]
        openssl_ref: [ 'openssl-3.5.0' ]

  test_rsync:
    runs-on: ubuntu-22.04
    needs: build_wolfprovider
    timeout-minutes: 15
    container:
      image: debian:bookworm
      env:
        DEBIAN_FRONTEND: noninteractive
    strategy:
      matrix:
        # Test 5.8.2 since our .deb is based on that version
        rsync_ref: [ 'v3.2.7' ]
        wolfssl_ref: [ 'v5.8.2-stable' ]
        openssl_ref: [ 'openssl-3.5.0' ]
        force_fail: [ 'WOLFPROV_FORCE_FAIL=1', '' ]
    steps:
      - name: Set up environment
        run: |
          apt-get update
          apt-get install -y git sudo build-essential autoconf automake \
            libtool pkg-config libjansson-dev check ca-certificates dpkg-dev

      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download wolfSSL packages
        uses: actions/download-artifact@v4
        with:
          name: wolfssl-debian-packages-${{ github.sha }}
          path: /tmp/wolfssl-artifacts

      - name: Download OpenSSL/wolfProvider packages
        uses: actions/download-artifact@v4
        with:
          name: openssl-wolfprov-debian-packages-${{ github.sha }}
          path: /tmp/openssl-wolfprov-artifacts

      - name: Install wolfSSL/OpenSSL/wolfprov packages
        run: |
          $GITHUB_WORKSPACE/.github/scripts/install-packages.sh
  
      - name: Install rsync dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y gcc g++ gawk python3-cmarkgfm \
            acl libacl1-dev attr libattr1-dev libxxhash-dev \
            libzstd-dev liblz4-dev

      - name: Checkout rsync
        uses: actions/checkout@v4
        with:
          repository: RsyncProject/rsync
          path: rsync_repo
          ref: ${{ matrix.rsync_ref }}
          fetch-depth: 1

      - name: Build and install rsync
        working-directory: rsync_repo
        run: |
          ./configure --disable-xxhash

          # Run the patch script from wolfProvider
          $GITHUB_WORKSPACE/.github/scripts/add-rsync-sha-test.sh

          make -j$(nproc)
          #export RSYNC_CHECKSUM_LIST="none"
          #This can disable file checksums which currently use rsycs own implementation of MD4 and MD5
          #Causes a lot of tests in the make check to fail so im keeping it disabled

      - name: Run rsync tests
        working-directory: rsync_repo
        run: |
          # wolfProvider is already loaded as the default provider
          echo "Current OpenSSL providers:"
          openssl list -providers
          openssl list -providers | grep -q "wolfSSL Provider" || (echo "ERROR: libwolfprov not found in OpenSSL providers" && exit 1)
          export ${{ matrix.force_fail }}

          # Run rsync test suite including our SHA test
          make check 2>&1 | tee rsync-test.log

          # Check test results - look for "0 failed" in the output
          if grep -q "overall result is 0" rsync-test.log; then
            TEST_RESULT=0
          else
            TEST_RESULT=1
          fi

          $GITHUB_WORKSPACE/.github/scripts/check-workflow-result.sh $TEST_RESULT ${{ matrix.force_fail }} rsync
