name: Simple Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ '*' ]
#    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  make_check:
    strategy:
      matrix:
        config: [
          # Add new configs here
          '',
          'OPENSSL_TAG=master',
          'WOLFSSL_TAG=master',
          'OPENSSL_TAG=master WOLFSSL_TAG=master',
        ]
    name: make check
    runs-on: ubuntu-latest
    # This should be a safe limit for the tests to run.
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Checkout wolfProvider

      - name: Test wolfProvider
        run: |
          ${{ matrix.config }} ./scripts/build-wolfprovider.sh
          make check
          ./scripts/cmd_test/do-cmd-tests.sh

      - name: Print errors 
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
