name: Simple Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  simple_test:
    name: Simple Test
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04-arm]
        openssl_ref: [ 'master', 'openssl-3.5.0' ]
        wolfssl_ref: [ 'master', 'v5.8.0-stable' ]
        force_fail: ['WOLFPROV_FORCE_FAIL=1', '']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Retrieving wolfSSL/wolfProvider from cache
        uses: actions/cache/restore@v4
        id: wolfprov-cache
        with:
          path: |
            scripts
            wolfssl-source
            wolfssl-install
            wolfprov-install
            openssl-install
            provider.conf

          key: wolfprov-${{ matrix.os }}-${{ matrix.wolfssl_ref }}-${{ matrix.openssl_ref }}-${{ github.sha }}
          fail-on-cache-miss: true

      # If not yet built this version, build it now
      - name: Build wolfProvider
        if: steps.wolfprov-cache.outputs.cache-hit != 'true'
        run: |
          OPENSSL_TAG=${{ matrix.openssl_ref }} WOLFSSL_TAG=${{ matrix.wolfssl_ref }} ./scripts/build-wolfprovider.sh

      - name: Run simple tests
        run: |
          ./scripts/cmd_test/do-cmd-tests.sh ${{ matrix.force_fail }}

      - name: Print test logs
        if: always()
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
