name: Simple Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build-wolfprovider:
    uses: ./.github/workflows/build-wolfprovider.yml
    with:
      os_ref: ${{ matrix.os_ref }}
      wolfssl_ref: ${{ matrix.wolfssl_ref }}
      openssl_ref: ${{ matrix.openssl_ref }}
    strategy:
      matrix:
        os_ref: [ 'ubuntu-22.04', 'ubuntu-24.04-arm' ]
        wolfssl_ref: [ 'master', 'v5.8.0-stable' ]
        openssl_ref: [ 'master', 'openssl-3.5.0' ]

  simple_test:
    name: Simple Test
    timeout-minutes: 20
    strategy:
      matrix:
        os_ref: [ 'ubuntu-22.04', 'ubuntu-24.04-arm' ]
        openssl_ref: [ 'master', 'openssl-3.5.0' ]
        wolfssl_ref: [ 'master', 'v5.8.0-stable' ]
        force_fail: ['WOLFPROV_FORCE_FAIL=1', '']
    runs-on: ${{ matrix.os_ref }}
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Retrieving wolfSSL/wolfProvider from cache
        uses: actions/cache/restore@v4
        id: wolfprov-cache
        with:
          path: |
            scripts
            wolfssl-source
            wolfssl-install
            wolfprov-install
            openssl-install
            provider.conf

          key: wolfprov-${{ matrix.os_ref }}-${{ matrix.wolfssl_ref }}-${{ matrix.openssl_ref }}-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Run simple tests
        run: |
          ./scripts/cmd_test/do-cmd-tests.sh ${{ matrix.force_fail }}

      - name: Print test logs
        if: always()
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
