name: systemd Tests

# START OF COMMON SECTION
on:
  push:
    branches: ['master', 'main', 'release/**']
  pull_request:
    branches: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    uses: ./.github/workflows/build-wolfprovider.yml
    with:
      wolfssl_ref: ${{ matrix.wolfssl_ref }}
      openssl_ref: ${{ matrix.openssl_ref }}
    strategy:
      matrix:
        wolfssl_ref: ['v5.8.2-stable']
        openssl_ref: ['openssl-3.5.0']

  test_systemd:
    runs-on: ubuntu-22.04
    needs: build_wolfprovider
    container:
      image: debian:bookworm
      env:
        DEBIAN_FRONTEND: noninteractive
    # This should be a safe limit for the tests to run.
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        # Test 5.8.2 since our .deb is based on that version
        systemd_ref: ['v254']
        wolfssl_ref: ['v5.8.2-stable']
        openssl_ref: ['openssl-3.5.0']
        force_fail: ['WOLFPROV_FORCE_FAIL=1', '']
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential meson ninja-build \
            libmount-dev gperf python3-pytest libuv1-dev libnghttp2-dev \
            libcap-dev uuid-dev libdevmapper-dev libpopt-dev libjson-c-dev \
            libargon2-dev libblkid-dev asciidoctor pkgconf zlib1g-dev

      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download wolfSSL packages
        uses: actions/download-artifact@v4
        with:
          name: wolfssl-debian-packages-${{ github.sha }}
          path: /tmp/wolfssl-artifacts

      - name: Download OpenSSL/wolfProvider packages
        uses: actions/download-artifact@v4
        with:
          name: openssl-wolfprov-debian-packages-${{ github.sha }}
          path: /tmp/openssl-wolfprov-artifacts

      - name: Install wolfSSL/OpenSSL/wolfprov packages
        run: |
          $GITHUB_WORKSPACE/.github/scripts/install-packages.sh

      - name: Checkout systemd
        uses: actions/checkout@v4
        with:
          repository: systemd/systemd
          path: systemd
          fetch-depth: 1
          ref: ${{ matrix.systemd_ref }}

      - name: Build systemd
        working-directory: systemd
        run: |
          meson setup -Dnobody-group=nogroup build
          ninja -C build

      - name: Run systemd tests
        working-directory: systemd
        run: |
          set +e
          # wolfProvider is already loaded as the default provider
          echo "Current OpenSSL providers:"
          openssl list -providers
          openssl list -providers | grep -q "wolfSSL Provider" || (echo "ERROR: libwolfprov not found in OpenSSL providers" && exit 1)
          # The following test cases link directly to libcrypto.
          TEST_CASES="fuzz-dns-packet fuzz-etc-hosts fuzz-resource-record \
                      resolvectl systemd-resolved test-cryptolib \
                      test-dns-packet test-dnssec test-resolve-tables \
                      test-resolved-etc-hosts test-resolved-packet \
                      test-resolved-stream"
          export ${{ matrix.force_fail }}
          meson test -C build $TEST_CASES
          TEST_RESULT=$?
          $GITHUB_WORKSPACE/.github/scripts/check-workflow-result.sh $TEST_RESULT ${{ matrix.force_fail }} systemd
